TercerParcial_Ortiz/Controllers/PaginasOrtizController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TercerParcial_Ortiz;
using TercerParcial_Ortiz.Models;

namespace TercerParcial_Ortiz.Controllers
{
    public class PaginasOrtizController : Controller
    {
        private OrkutUAAEntities db = new OrkutUAAEntities();

        public ActionResult PaginasOrtiz()
        {
            var lst = db.Pagina.ToList().Take(10);
            return View(lst);
        }

        public ActionResult ParaTiOrtiz()
        {
            var lst = db.Pagina.OrderByDescending(x => x.CantidadLikes).Take(1);
            int cantProgramacion = db.Pagina.Where(x => x.Categoria == "Programación").Count();
            double? promedioLikes = db.Pagina.Where(x => x.Ciudad == "Asuncion").Average(x => x.CantidadLikes);
            ViewBag.cantProgramacion = "Cantidad de paginas de la categoria programacion= " + cantProgramacion;
            ViewBag.Promedio = "El promedio de likes de las páginas que sean de la ciudad de Asunción= " + promedioLikes;
            return View(lst);
        }
    }
}

TercerParcial_Ortiz/Controllers/PublicacionesOrtizController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using TercerParcial_Ortiz.Models;

namespace TercerParcial_Ortiz.Controllers
{
    public class PublicacionesOrtizController : Controller
    {
        private OrkutUAAEntities db = new OrkutUAAEntities();

        // GET: PublicacionesOrtiz
        public ActionResult Index()
        {
            return View(db.Publicacion.ToList());
        }

        // GET: PublicacionesOrtiz/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacion publicacion = db.Publicacion.Find(id);
            if (publicacion == null)
            {
                return HttpNotFound();
            }
            return View(publicacion);
        }

        // GET: PublicacionesOrtiz/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PublicacionesOrtiz/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Fecha,Mes,Titulo,Texto")] Publicacion publicacion)
        {
            if (ModelState.IsValid)
            {
                publicacion.Mes = DateTime.Now.Month;
                publicacion.Fecha = DateTime.Now;
                db.Publicacion.Add(publicacion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(publicacion);
        }

        // GET: PublicacionesOrtiz/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacion publicacion = db.Publicacion.Find(id);
            if (publicacion == null)
            {
                return HttpNotFound();
            }
            return View(publicacion);
        }

        // POST: PublicacionesOrtiz/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Fecha,Mes,Titulo,Texto")] Publicacion publicacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publicacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publicacion);
        }

        // GET: PublicacionesOrtiz/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacion publicacion = db.Publicacion.Find(id);
            if (publicacion == null)
            {
                return HttpNotFound();
            }
            return View(publicacion);
        }

        // POST: PublicacionesOrtiz/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Publicacion publicacion = db.Publicacion.Find(id);
            db.Publicacion.Remove(publicacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult MesOrtiz(int? mes)
        {
            if (mes == null)
            {
                mes = 11;
            }
            var lstpublicacion = db.Publicacion.ToList().Where(x => x.Mes == mes);
            return View(lstpublicacion);
        }
    }
}

TercerParcial_Ortiz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("OrkutUAA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Caracteristicas", "CaracteristicasOrtiz", "Home")</li>
                    <li>@Html.ActionLink("Publicaciones", "Index", "PublicacionesOrtiz")</li>
                    <li>@Html.ActionLink("Para Ti", "ParaTiOrtiz", "PaginasOrtiz")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi Tercer Parcial de .NET. Todos los derechos reservados.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>